### ISSUE TITLE
Exception when making a connection.

### ISSUE THREAD

**Issue by Qubiz** [dji-sdk/Android-Bridge-App#1]
**The issue is resolved when using the new version of the DJI SDK (4.0.1)**

When I try to create a connection between my emulator and bridge app, the app on my emulator crashes and show the following errors shown below. The bridge application shows that there is a connection for a brief moment, but disconnects quickly afterwards. Maybe this is a problem with the DJI SDK and not the bridge app though.

````
04-08 11:25:39.457 13179-13218/utwente.uav.uavdisasterprobev2 D/enableBridgeMode: ip: 192.168.2.4
04-08 11:25:39.458 13179-13218/utwente.uav.uavdisasterprobev2 E/DJIUsbAccessoryReceiver: start accessory receiver
                                                                                         
                                                                                         [ 04-08 11:25:39.466 13179:13218 E/         ]
                                                                                         stopDaemon AOA
04-08 11:25:39.467 13179-13218/utwente.uav.uavdisasterprobev2 E/d: djisocket destroy
04-08 11:25:39.467 13179-13218/utwente.uav.uavdisasterprobev2 E/daemon: destroy wifi 1
04-08 11:25:39.467 13179-13218/utwente.uav.uavdisasterprobev2 E/b: djisocket destroy
04-08 11:25:39.468 13179-13218/utwente.uav.uavdisasterprobev2 E/daemon: destroy wifi 2
04-08 11:25:39.469 13179-13218/utwente.uav.uavdisasterprobev2 E/c: udt destroy 1 9000
04-08 11:25:39.469 13179-13218/utwente.uav.uavdisasterprobev2 E/c: udt destroy 2 9000
04-08 11:25:39.469 13179-13218/utwente.uav.uavdisasterprobev2 E/daemon: destroy wifi 3
04-08 11:25:39.470 13179-13218/utwente.uav.uavdisasterprobev2 E/a: udt destroy 1 9001
04-08 11:25:39.470 13179-13218/utwente.uav.uavdisasterprobev2 E/a: udt destroy 2 9001
04-08 11:25:39.470 13179-13218/utwente.uav.uavdisasterprobev2 E/daemon: destroy wifi 4
04-08 11:25:39.470 13179-13218/utwente.uav.uavdisasterprobev2 E/daemon: destroy wifi 4
                                                                        
                                                                        [ 04-08 11:25:39.471 13179:13218 D/         ]
                                                                        ===DJIProductManager===[AOA]
                                                                        
                                                                        [ 04-08 11:25:39.472 13179:13218 D/         ]
                                                                        ===rcType bylink===[litchiX]
04-08 11:25:39.473 13179-13218/utwente.uav.uavdisasterprobev2 D/DJIComponentManager: Sat Apr 08 11:25:39 EDT 2017DJILinkType linkType
                                                                                     
                                                                                     [ 04-08 11:25:39.473 13179:13218 D/         ]
                                                                                     linkType=AOA
04-08 11:25:39.515 13179-13218/utwente.uav.uavdisasterprobev2 D/UsbAccessoryService: recvBufferThread.start
04-08 11:25:39.516 13179-13218/utwente.uav.uavdisasterprobev2 D/UsbAccessoryService: parseVideoFromCamThread.start
04-08 11:25:39.518 13179-13385/utwente.uav.uavdisasterprobev2 D/UsbAccessoryService: Camera ParseVideoRunnable false
04-08 11:25:39.518 13179-13385/utwente.uav.uavdisasterprobev2 D/UsbAccessoryService: ParseVideoRunnable.end
04-08 11:25:39.518 13179-13218/utwente.uav.uavdisasterprobev2 D/UsbAccessoryService: parseVideoFromFpvThread.start
04-08 11:25:39.518 13179-13218/utwente.uav.uavdisasterprobev2 D/enableBridgeMode: end
04-08 11:25:39.518 13179-13218/utwente.uav.uavdisasterprobev2 E/UAVDisasterProbeApplication: API Key successfully registered
04-08 11:25:39.518 13179-13386/utwente.uav.uavdisasterprobev2 D/UsbAccessoryService: Fpv ParseVideoRunnable false
04-08 11:25:39.518 13179-13386/utwente.uav.uavdisasterprobev2 D/UsbAccessoryService: ParseVideoRunnable.end
04-08 11:25:39.523 13179-13384/utwente.uav.uavdisasterprobev2 D/UsbAccessoryService: RecvOsdRunnable false
04-08 11:25:39.670 13179-13382/utwente.uav.uavdisasterprobev2 E/DJICrashHandler: uncaughtException 2
04-08 11:25:39.672 13179-13382/utwente.uav.uavdisasterprobev2 E/UsbAccessoryService: final destroy() 71
04-08 11:25:39.773 13179-13382/utwente.uav.uavdisasterprobev2 E/UsbAccessoryService: final destroy() 72
04-08 11:25:39.773 13179-13382/utwente.uav.uavdisasterprobev2 E/wm220: ****resetSwitchFromWifiFlag
04-08 11:25:39.773 13179-13382/utwente.uav.uavdisasterprobev2 E/DJIUsbAccessoryReceiver: receiver destroySession
04-08 11:25:39.773 13179-13382/utwente.uav.uavdisasterprobev2 E/UsbAccessoryService: final destroy() 73
04-08 11:25:39.773 13179-13382/utwente.uav.uavdisasterprobev2 E/UsbAccessoryService: final destroy() 75
04-08 11:25:39.773 13179-13382/utwente.uav.uavdisasterprobev2 E/UsbAccessoryService: final destroy() 76
04-08 11:25:39.773 13179-13382/utwente.uav.uavdisasterprobev2 E/DJICrashHandler: uncaughtException 3
04-08 11:25:39.805 13179-13179/utwente.uav.uavdisasterprobev2 D/DJIRemoteVersionInfo: UpgradeConfigInfo getFile for net success
04-08 11:25:39.973 13179-13382/utwente.uav.uavdisasterprobev2 E/DJICrashHandler: uncaughtException 4
04-08 11:25:39.973 13179-13382/utwente.uav.uavdisasterprobev2 E/AndroidRuntime: FATAL EXCEPTION: Thread-32
                                                                                Process: utwente.uav.uavdisasterprobev2, PID: 13179
                                                                                java.lang.AbstractMethodError: abstract method "void org.java_websocket.client.WebSocketClient.onOpen(org.java_websocket.handshake.ServerHandshake)"
                                                                                    at org.java_websocket.client.WebSocketClient.onWebsocketOpen(WebSocketClient.java:328)
                                                                                    at org.java_websocket.WebSocketImpl.open(WebSocketImpl.java:649)
                                                                                    at org.java_websocket.WebSocketImpl.decodeHandshake(WebSocketImpl.java:276)
                                                                                    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:159)
                                                                                    at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230)
                                                                                    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
                                                                                    at java.lang.Thread.run(Thread.java:761)
04-08 11:25:39.977 13179-13218/utwente.uav.uavdisasterprobev2 D/nfz: refresh db
04-08 11:25:39.978 13179-13218/utwente.uav.uavdisasterprobev2 D/nfz: DataFlycGetPushRequestLimitUpdate in, serialnumber: 
04-08 11:25:39.980 13179-13382/utwente.uav.uavdisasterprobev2 I/Process: Sending signal. PID: 13179 SIG: 9
````

**Comment by talobin** [comment]
The log that you get is from the SDK side.
Not from the Bridge.

We have released a new version 1.2.0
Please check it out with the new SDK 4.4.0.

Thanks!
